@Library('Shared') _
pipeline {
    agent { label 'agent' }
    
    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'Frontend Docker tag of the image built by the CI job')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Backend Docker tag of the image built by the CI job')
    }

    stages {
        stage("Workspace cleanup") {
            steps {
                script {
                    cleanWs()
                }
            }
        }
        
        stage('Git: Code Checkout') {
            steps {
                script {
                    code_checkout("https://github.com/maverick96k/Jenkins-CICD-Project.git", "main")
                }
            }
        }
        
        stage('Verify: Docker Image Tags') {
            steps {
                script {
                    echo "FRONTEND_DOCKER_TAG: ${params.FRONTEND_DOCKER_TAG}"
                    echo "BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
                }
            }
        }
        
        stage("Update: Kubernetes manifests") {
            steps {
                script {
                    dir('kubernetes') {
                        sh """
                            sed -i -e s/wanderlust-backend-beta.*/wanderlust-backend-beta:${params.BACKEND_DOCKER_TAG}/g backend.yaml
                        """
                    }
                    
                    dir('kubernetes') {
                        sh """
                            sed -i -e s/wanderlust-frontend-beta.*/wanderlust-frontend-beta:${params.FRONTEND_DOCKER_TAG}/g frontend.yaml
                        """
                    }
                }
            }
        }
        
        stage("Git: Code update and push to GitHub") {
            steps {
                script {
                    withCredentials([gitUsernamePassword(credentialsId: 'github-cred', gitToolName: 'Default')]) {
                        sh '''
                            echo "Checking repository status: "
                            git status
                        
                            echo "Adding changes to git: "
                            git add .
                            
                            echo "Committing changes: "
                            git commit -m "Updated environment variables"
                            
                            echo "Pushing changes to GitHub: "
                            git push https://github.com/maverick96k/Jenkins-CICD-Project.git main
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo """
            ====================================================
            ✅  Build Successful
            ----------------------------------------------------
            Project: ${env.JOB_NAME}
            Build Number: ${env.BUILD_NUMBER}
            URL: ${env.BUILD_URL}
            ====================================================
            """
        }
        failure {
            echo """
            ====================================================
            ❌  Build Failed
            ----------------------------------------------------
            Project: ${env.JOB_NAME}
            Build Number: ${env.BUILD_NUMBER}
            URL: ${env.BUILD_URL}
            ====================================================
            """
        }
    }
}
